/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.2/samples
 */

plugins {
    `java-library`
    id("application")
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

val groupId: String by project
val edcVersion: String by project

dependencies {
    implementation("$groupId:runtime-metamodel:$edcVersion")

    implementation("$groupId:control-plane-core:$edcVersion")

    implementation("$groupId:api-observability:$edcVersion")

    implementation("$groupId:configuration-filesystem:$edcVersion")
    implementation("$groupId:vault-filesystem:$edcVersion")
    implementation("$groupId:iam-mock:$edcVersion")

    implementation("$groupId:auth-tokenbased:$edcVersion")
    implementation("$groupId:management-api:$edcVersion")

    implementation("$groupId:dsp:$edcVersion")

    implementation("$groupId:data-plane-aws-s3:$edcVersion")
    implementation("$groupId:data-plane-azure-storage:$edcVersion")
    implementation("$groupId:data-plane-http:$edcVersion")

    implementation("$groupId:data-plane-core:$edcVersion")
    implementation("$groupId:data-plane-api:$edcVersion")

    implementation("$groupId:data-plane-selector-core:$edcVersion")
    implementation("$groupId:data-plane-selector-client:$edcVersion")
    implementation("$groupId:data-plane-selector-api:$edcVersion")

    implementation("$groupId:transfer-data-plane:$edcVersion")

    implementation(project(":federated-catalog"))
}

application {
    mainClass.set("org.eclipse.edc.boot.system.runtime.BaseRuntime")
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar> {
    exclude("**/pom.properties", "**/pom.xm")
    mergeServiceFiles()
    archiveFileName.set("connector.jar")
}
